export const QA_KIT_DEP = "github:TangoGroup/qa-kit#main";

export function renderQaConfig(input: {
  appName: string; repo: string;
  actions?: string; apiRoutes?: string; publicRoutes?: string[];
}): string {
  const publics = (input.publicRoutes ?? ["app/api/auth/**"]).map((p) => `"${p}"`).join(", ");
  return `import { defineQAConfig } from "qa-kit/core";

// Generated by qa-kit \`/qa-init\`. Replace every TODO_ placeholder with real
// values for this app, then remove this comment. The TODO_ values are valid
// (non-empty) so the config still loads; they are NOT correct for your app.
export default defineQAConfig({
  app: { name: "${input.appName}", repo: "${input.repo}" },
  tenancy: {
    key: "TODO_tenantKey",                 // the tenant discriminator column, e.g. "campusId"
    accessHelper: "TODO_assertTenantAccess", // the canonical guard fn name
    bypassRoles: ["TODO_superAdminRole"],    // roles with global bypass (optional)
  },
  personas: {
    // source: "./e2e/_lib/personas.ts", loginAs: "loginAs",
    matrix: ["TODO_role"],                   // the roles to exercise
  },
  envs: {
    staging: { baseUrl: "https://TODO.example.com", healthPath: "/api/health" },
  },
  surface: {
    actions: "${input.actions ?? "app/**/actions.ts"}",
    apiRoutes: "${input.apiRoutes ?? "app/api/**/route.ts"}",
    publicRoutes: [${publics}],
  },
  findings: { dir: "qa-testing/findings", githubLabels: ["qa", "auto-found"] },
});
`;
}
